### ISSUE TITLE
it doesn't saves notes for relatively long time

### ISSUE THREAD

**Issue by Gerodote** [TomSmeets/TodoTree#3]
1. make some notes
2. exit
3. return to the app |=> everything is fine
4. exit and wait some time, e.g. a day
5. return to the app |=> all notes disappeared

i saw this behavior at least twice

samsung Android 13

**Comment by Gerodote** [comment]
oh i checked this on 1.2 cuz 1.3 isnt at fdroid

**Comment by TomSmeets** [comment]
Yes this was a bad bug in 1.2, it should be fixed in 1.3
